services:
  client:
    container_name: boycott-this-client
    build:
      context: .
      dockerfile: client/dockerfile
    image: boycott-this-client
    volumes:
      - ./client:/client
      - /client/node_modules
    ports:
      - "3000:3000"
    environment:
      PORT: "3000"
    restart: unless-stopped
  api:
    container_name: boycott-this-api
    build:
      context: .
      dockerfile: api/dockerfile
    image: boycott-this-api
    volumes:
      - type: bind
        source: ./api
        target: /api
    ports:
      - "8000:8000"
    restart: unless-stopped